name: Check for Broken Links

on:
  push:
    branches: [ main ]   # Runs on pushes to the 'main' branch
  schedule:
    - cron: '0 1 * * *'   # Runs every day at 01:00 AM UTC

jobs:
  link-check:
    name: Lychee Link Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lychee
        run: |
          curl -LsSf https://github.com/lycheeverse/lychee/releases/latest/download/lychee-linux.zip -o lychee.zip
          unzip lychee.zip
          chmod +x lychee
          sudo mv lychee /usr/local/bin

      - name: Run link checker
        run: |
          lychee --verbose --exclude-mail --no-progress . || true
